# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test Calendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MaterialComponents/Buttons', '33.0.0'
  pod "Koyomi", '1.2.6'
  pod 'RealmSwift','2.4.3'
  pod 'Alamofire','4.0.0'
  pod 'SwiftyJSON','3.1'

  # Pods for Test Calendar

  target 'Test CalendarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test CalendarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
